---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: poetica-amd64
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: poetica-amd64-secret
    template:
      data:
        github_app_id: '{{ .ACTIONS_RUNNER_APP_ID }}'
        github_app_installation_id: '{{ .ACTIONS_RUNNER_INSTALLATION_ID }}'
        github_app_private_key: '{{ .ACTIONS_RUNNER_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: poetica-amd64-actions-runner
