[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
ROOT_DIR = "{{config_root}}"
KUBECONFIG = "{{ env.HOME }}/.kube/configs/config.homelab"
TALOSCONFIG = '{{config_root}}/talos/clusterconfig/talosconfig'
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"

[tools]
"python" = "3.14.0"
"pipx:makejinja" = "2.8.2"
"aqua:budimanjojo/talhelper" = "3.0.36"
"aqua:cilium/cilium-cli" = "0.18.7"
"aqua:cli/cli" = "2.83.0"
"aqua:cue-lang/cue" = "0.15.1"
"aqua:cloudflare/cloudflared" = "2025.11.1"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.7.0"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.45.5"
"aqua:helmfile/helmfile" = "1.2.2"
"aqua:helm/helm" = "4.0.1"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.49.2"
"aqua:siderolabs/talos" = "1.11.2"
"aqua:yannh/kubeconform" = "0.7.0"
