---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/alerts
  - ../../components/registry-creds

resources:
  - ./namespace.yaml
  - ./atuin/ks.yaml
  - ./backlogs/ks.yaml
  - ./bentopdf/ks.yaml
  - ./cyberchef/ks.yaml
  - ./excalidraw/ks.yaml
  - ./gitea/ks.yaml
  - ./home-api/ks.yaml
  - ./karakeep/ks.yaml
  - ./mealie/ks.yaml
  - ./opengist/ks.yaml
  - ./openspeedtest/ks.yaml
  - ./outline/ks.yaml
  - ./pairdrop/ks.yaml
  - ./paperless/ks.yaml
  - ./shlink/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./umami/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./wallos/ks.yaml
  - ./wheel/ks.yaml
