---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-crunchy-postgres"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .MINIO_AWS_ACCESS_KEY }}
          repo1-s3-key-secret={{ .MINIO_AWS_SECRET_KEY }}
          repo2-s3-key={{ .B2_AWS_ACCESS_KEY }}
          repo2-s3-key-secret={{ .B2_AWS_SECRET_KEY }}

        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .BACKUP_ENCRYPTION_KEY }}
          repo2-cipher-pass={{ .BACKUP_ENCRYPTION_KEY }}
  dataFrom:
    - extract:
        key: crunchy-postgres
    - extract:
        key: s3
    - extract:
        key: volsync-minio
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MINIO_$1"
    - extract:
        key: volsync-b2
      rewrite:
        - regexp:
            source: "(.*)"
            target: "B2_$1"
