---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName listmonk-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *secretName
    template:
      type: Opaque
      data:
        LISTMONK_db__user: '{{ index . "user" }}'
        LISTMONK_db__password: '{{ index . "password" }}'
        LISTMONK_db__database: '{{ index . "dbname" }}'
        LISTMONK_db__host: '{{ index . "host" }}'
        LISTMONK_db__port: '{{ index . "port" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-listmonk

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: listmonk
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: listmonk-secret
    template:
      type: Opaque
      data:
        LISTMONK_ADMIN_USER: "{{ .LISTMONK_ADMIN_USER }}"
        LISTMONK_ADMIN_PASSWORD: "{{ .LISTMONK_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: listmonk
